name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_db1"
database_id = "13761d44-39e8-4527-99e7-205850cb6fd0"

[version_metadata]
binding = "CF_VERSION_METADATA"
